export const envKeys = {
  DATABASE_URL: "DATABASE_URL",
  API_PORT: "API_PORT",
  WEB_PORT: "WEB_PORT",
  AI_SERVICE_PORT: "AI_SERVICE_PORT",
  AI_SERVICE_BASE_URL: "AI_SERVICE_BASE_URL",
  AI_SERVICE_TOKEN: "AI_SERVICE_TOKEN",
  AI_SERVICE_TIMEOUT_MS: "AI_SERVICE_TIMEOUT_MS",
  INTERNAL_SERVICE_TOKEN: "INTERNAL_SERVICE_TOKEN",
  AI_LLM_PROVIDER: "AI_LLM_PROVIDER",
  GEMINI_API_KEY: "GEMINI_API_KEY",
  GEMINI_MODEL: "GEMINI_MODEL",
  GEMINI_API_BASE_URL: "GEMINI_API_BASE_URL",
  GEMINI_TIMEOUT_MS: "GEMINI_TIMEOUT_MS",
  OPENAI_MODEL: "OPENAI_MODEL",
  JWT_SECRET: "JWT_SECRET",
  LINE_CHANNEL_SECRET: "LINE_CHANNEL_SECRET",
  LINE_CHANNEL_ACCESS_TOKEN: "LINE_CHANNEL_ACCESS_TOKEN",
  LINE_CHANNEL_ID: "LINE_CHANNEL_ID",
  LINE_REPLY_TIMEOUT_MS: "LINE_REPLY_TIMEOUT_MS",
  OPENAI_API_KEY: "OPENAI_API_KEY",
  CHECKPOINT_DISABLE: "CHECKPOINT_DISABLE",
  NODE_ENV: "NODE_ENV",
} as const;

export const envExample = {
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/chatto_phase2?schema=public",
  API_PORT: "4000",
  WEB_PORT: "3000",
  AI_SERVICE_PORT: "5000",
  AI_SERVICE_BASE_URL: "http://localhost:5000",
  AI_SERVICE_TOKEN: "dev_internal_service_token",
  AI_SERVICE_TIMEOUT_MS: "12000",
  INTERNAL_SERVICE_TOKEN: "dev_internal_service_token",
  AI_LLM_PROVIDER: "mock",
  GEMINI_API_KEY: "",
  GEMINI_MODEL: "gemini-3.5-flash",
  GEMINI_API_BASE_URL: "https://generativelanguage.googleapis.com/v1beta/interactions",
  GEMINI_TIMEOUT_MS: "7000",
  OPENAI_MODEL: "",
  JWT_SECRET: "change-me-for-local-development",
  LINE_CHANNEL_SECRET: "phase-2-placeholder-secret",
  LINE_CHANNEL_ACCESS_TOKEN: "phase-2-placeholder-token",
  LINE_CHANNEL_ID: "2010446906",
  LINE_REPLY_TIMEOUT_MS: "5000",
  OPENAI_API_KEY: "phase-2-placeholder-key",
  CHECKPOINT_DISABLE: "1",
  NODE_ENV: "development",
} as const;

export const defaultPorts = {
  api: 4000,
  web: 3000,
  aiService: 5000,
  postgres: 5432,
} as const;

export type SharedEnvKey = keyof typeof envKeys;
